version: "3"

services:

  backend:
    image: mjsasha/backend:2.1.1
    container_name: backend_2.1.1
    restart: always
    depends_on: 
      - db
    ports:
      - "8080:8080"
    environment:
      UPLOADED_FILES_FOLDER_PATH: /uploaded-files
      POSTGRES_DB: les-doc
      PSQL_HOST: db
      PSQL_PORT: 5432
      PSQL_USER: admin
      PSQL_PASSWORD: admin

  db:
    image: postgres:14.2
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: les-doc

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "5000:8080"