version: "3"

services:

  backend:
    image: mjsasha/backend:2.1.4
    container_name: backend_2.1.4
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      UPLOADED_FILES_FOLDER_PATH: /uploaded-files