server:
  servlet:
    context-path: /api
  port: 8081
spring:
  profiles:
    active: prod
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
file:
  upload-dir: ${UPLOADED_FILES_FOLDER_PATH:/uploaded-files}
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:les-doc
    driverClassName: org.h2.Driver
    username: admin
    password: admin
services:
  orchestrator-origin: http://localhost:8080
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${PSQL_HOST:0.0.0.0}:${PSQL_PORT:5432}/${POSTGRES_DB:les-doc}
    username: ${PSQL_USER:admin}
    password: ${PSQL_PASSWORD:admin}
services:
  orchestrator-origin: ${ORCHESTRATOR_ORIGIN:http://localhost:8080}