server:
  servlet:
    context-path: /api
  port: 8081
spring:
  profiles:
    active: prod
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  jpa:
    hibernate:
      ddl-auto: update
file:
  upload-dir: ${UPLOADED_FILES_FOLDER_PATH:/uploaded-files}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:les-doc
    driverClassName: org.h2.Driver
    username: admin
    password: admin
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/les-doc
    username: admin
    password: admin
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${PSQL_HOST:0.0.0.0}:${PSQL_PORT:5432}/${POSTGRES_DB:les-doc}
    username: ${PSQL_USER:admin}
    password: ${PSQL_PASSWORD:admin}
  kafka:
    producer:
      bootstrap-servers: localhost:${KAFKA_PORT:9092}
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: 8080