server:
  servlet:
    context-path: /api
  port: 8080
spring:
  profiles:
    active: prod
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
---
spring:
  config:
    activate:
      on-profile: dev
services:
  convertor-origin: http://localhost:8083/api
  files-and-lessons-origin: http://localhost:8081/api
  statistic-origin: http://localhost:8082/api
---
spring:
  config:
    activate:
      on-profile: prod
services:
  convertor-origin: ${FILES_AND_LESSONS_ORIGIN:http://localhost:8083/api}
  files-and-lessons-origin: ${FILES_AND_LESSONS_ORIGIN:http://localhost:8081/api}
  statistic-origin: ${FILES_AND_LESSONS_ORIGIN:http://localhost:8082/api}