spring:
  profiles:
    active: prod
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    consumer:
      group-id: statisticGroup
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/les-doc
    username: admin
    password: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
server:
  port: 8082
  servlet:
    context-path: /api
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${PSQL_HOST:0.0.0.0}:${PSQL_PORT:5432}/${POSTGRES_DB:les-doc}
    username: ${PSQL_USER:admin}
    password: ${PSQL_PASSWORD:admin}
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
server:
  port: 8080
  servlet:
    context-path: ${SERVICE_ROOT:/api}